// AIO.MS - Module Registry
// Central configuration for all 16 modules

import { ModuleInfo } from '@/types';

export const MODULES: ModuleInfo[] = [
  // ── Nhóm 1: Foundation ──────────────────────────
  {
    id: 'core',
    code: 'CORE',
    name: 'Admin & Core',
    nameVi: 'Quản trị Hệ thống',
    description: 'Đăng nhập, phân quyền (RBAC), cấu hình hệ thống',
    icon: 'Shield',
    color: 'hsl(217, 72%, 46%)',
    href: '/dashboard',
    group: 'foundation',
    isEnabled: true,
    order: 0,
  },
  {
    id: 'ims',
    code: 'IMS',
    name: 'IT Management',
    nameVi: 'Quản lý CNTT',
    description: 'Bảo mật, audit logs, quản lý tenant, hạ tầng công nghệ',
    icon: 'Server',
    color: 'hsl(250, 60%, 52%)',
    href: '/dashboard/ims',
    group: 'foundation',
    isEnabled: true,
    order: 1,
  },
  {
    id: 'hms',
    code: 'HMS',
    name: 'Human Resources',
    nameVi: 'Quản lý Nhân sự',
    description: 'Tổ chức, nhân viên, phòng ban, năng suất & quỹ lương',
    icon: 'Users',
    color: 'hsl(174, 65%, 40%)',
    href: '/dashboard/hms',
    group: 'foundation',
    isEnabled: true,
    order: 2,
  },

  // ── Nhóm 2: Operations ──────────────────────────
  {
    id: 'pms',
    code: 'PMS',
    name: 'Purchasing',
    nameVi: 'Quản lý Mua hàng',
    description: 'Quản lý đơn mua hàng, nhà cung cấp, vật tư',
    icon: 'ShoppingCart',
    color: 'hsl(30, 80%, 50%)',
    href: '/dashboard/pms',
    group: 'operations',
    isEnabled: true,
    order: 3,
  },
  {
    id: 'wms',
    code: 'WMS',
    name: 'Warehouse',
    nameVi: 'Quản lý Kho bãi',
    description: 'Quản lý kho bãi, cắt kho tự động, tồn kho',
    icon: 'Warehouse',
    color: 'hsl(200, 70%, 45%)',
    href: '/dashboard/wms',
    group: 'operations',
    isEnabled: true,
    order: 4,
  },
  {
    id: 'tms',
    code: 'TMS',
    name: 'Transport',
    nameVi: 'Quản lý Giao hàng',
    description: 'Logistics, giao nhận, tuyến đường, tracking',
    icon: 'Truck',
    color: 'hsl(280, 55%, 50%)',
    href: '/dashboard/tms',
    group: 'operations',
    isEnabled: true,
    order: 5,
  },

  // ── Nhóm 3: Market ──────────────────────────────
  {
    id: 'fms',
    code: 'FMS',
    name: 'Factory',
    nameVi: 'Quản lý Nhà máy',
    description: 'Sản xuất, thi đua, tối ưu năng suất nhà máy',
    icon: 'Factory',
    color: 'hsl(340, 65%, 48%)',
    href: '/dashboard/fms',
    group: 'market',
    isEnabled: true,
    order: 6,
  },
  {
    id: 'qms',
    code: 'QMS',
    name: 'Quality',
    nameVi: 'Quản lý Chất lượng',
    description: 'Kiểm duyệt chất lượng, QA/QC tự động',
    icon: 'CheckCircle',
    color: 'hsl(152, 60%, 42%)',
    href: '/dashboard/qms',
    group: 'market',
    isEnabled: true,
    order: 7,
  },
  {
    id: 'rms',
    code: 'RMS',
    name: 'R&D',
    nameVi: 'Nghiên cứu & Phát triển',
    description: 'Tạo mẫu, đổi mới sáng tạo, quản lý dự án R&D',
    icon: 'Lightbulb',
    color: 'hsl(45, 90%, 50%)',
    href: '/dashboard/rms',
    group: 'market',
    isEnabled: true,
    order: 8,
  },
  {
    id: 'mms',
    code: 'MMS',
    name: 'Marketing',
    nameVi: 'Quản lý Marketing',
    description: 'Chiến dịch, phễu marketing, đa nền tảng',
    icon: 'Megaphone',
    color: 'hsl(320, 75%, 55%)',
    href: '/dashboard/mms',
    group: 'market',
    isEnabled: true,
    order: 9,
  },
  {
    id: 'sms',
    code: 'SMS',
    name: 'Sales',
    nameVi: 'Quản lý Bán hàng',
    description: 'Chốt đơn, khách hàng trung thành, doanh số',
    icon: 'TrendingUp',
    color: 'hsl(15, 80%, 55%)',
    href: '/dashboard/sms',
    group: 'market',
    isEnabled: true,
    order: 10,
  },
  {
    id: 'oms',
    code: 'OMS',
    name: 'Orders',
    nameVi: 'Quản lý Đơn hàng',
    description: 'Ghi nhận, đồng bộ đơn hàng toàn vẹn',
    icon: 'ClipboardList',
    color: 'hsl(190, 70%, 42%)',
    href: '/dashboard/oms',
    group: 'market',
    isEnabled: true,
    order: 11,
  },
  {
    id: 'dms',
    code: 'DMS',
    name: 'Distributor',
    nameVi: 'Quản lý Phân phối',
    description: 'Mạng lưới đại lý, kênh phân phối',
    icon: 'Network',
    color: 'hsl(260, 55%, 52%)',
    href: '/dashboard/dms',
    group: 'market',
    isEnabled: true,
    order: 12,
  },

  // ── Nhóm 4: Finance & Command ───────────────────
  {
    id: 'ams',
    code: 'AMS',
    name: 'Accounting',
    nameVi: 'Quản lý Kế toán',
    description: 'Hạch toán, công nợ, hóa đơn tự động',
    icon: 'Calculator',
    color: 'hsl(38, 90%, 50%)',
    href: '/dashboard/ams',
    group: 'finance',
    isEnabled: true,
    order: 13,
  },
  {
    id: 'cms',
    code: 'CMS',
    name: 'Controlling',
    nameVi: 'Quản trị & Kiểm soát',
    description: 'Kiểm soát rủi ro, ngân sách, cân đối lỗ lãi',
    icon: 'Gauge',
    color: 'hsl(0, 70%, 55%)',
    href: '/dashboard/cms',
    group: 'finance',
    isEnabled: true,
    order: 14,
  },
  {
    id: 'bms',
    code: 'BMS',
    name: 'Business Intelligence',
    nameVi: 'BI & Báo cáo',
    description: 'Dashboard BI trực quan, phân tích thời gian thực',
    icon: 'BarChart3',
    color: 'hsl(220, 75%, 55%)',
    href: '/dashboard/bms',
    group: 'finance',
    isEnabled: true,
    order: 15,
  },
];

export const MODULE_GROUPS = {
  foundation: { name: 'Nền tảng', nameEn: 'Foundation', icon: 'Layers' },
  operations: { name: 'Vận hành', nameEn: 'Operations', icon: 'Settings' },
  market: { name: 'Thị trường', nameEn: 'Market', icon: 'Globe' },
  finance: { name: 'Tài chính & Chỉ huy', nameEn: 'Finance & Command', icon: 'Crown' },
} as const;

export function getModuleByCode(code: string): ModuleInfo | undefined {
  return MODULES.find((m) => m.code === code);
}

export function getModulesByGroup(group: ModuleInfo['group']): ModuleInfo[] {
  return MODULES.filter((m) => m.group === group);
}
