// AIO.MS - Module Registry
// Central configuration for all 17 modules

import { ModuleInfo } from '@/types';

export const MODULES: ModuleInfo[] = [
  // ── Nhóm đặc biệt: BI & Phân tích ────────────────
  {
    id: 'bms',
    code: 'BMS',
    name: 'Business Intelligence',
    nameVi: 'BI & Báo cáo',
    description: 'Dashboard BI trực quan, phân tích thời gian thực',
    icon: 'BarChart3',
    color: 'hsl(38, 90%, 50%)', // Vàng Accent
    href: '/dashboard/bms',
    group: 'bi',
    isEnabled: true,
    order: 0,
  },

  // ── Nhóm: System ──────────────────────────────────
  {
    id: 'core',
    code: 'CORE',
    name: 'Admin & Core',
    nameVi: 'Quản trị Hệ thống',
    description: 'Đăng nhập, phân quyền (RBAC), cấu hình hệ thống',
    icon: 'Shield',
    color: 'hsl(348, 75%, 46%)', // Đỏ Primary
    href: '/dashboard/core',
    group: 'system',
    isEnabled: true,
    order: 1,
  },
  {
    id: 'gms',
    code: 'GMS',
    name: 'Gateway Management System',
    nameVi: 'Cổng kết nối tích hợp',
    description: 'API, tích hợp e-Invoice, Máy chấm công, ERP SAP',
    icon: 'Network',
    color: 'hsl(348, 75%, 46%)',
    href: '/dashboard/gms',
    group: 'system',
    isEnabled: true,
    order: 2,
  },

  // ── Nhóm: Operations ──────────────────────────────
  {
    id: 'fms',
    code: 'FMS',
    name: 'Factory',
    nameVi: 'Quản lý Nhà máy',
    description: 'Sản xuất, thi đua, tối ưu năng suất nhà máy',
    icon: 'Factory',
    color: 'hsl(348, 75%, 46%)',
    href: '/dashboard/fms',
    group: 'operations',
    isEnabled: true,
    order: 3,
  },
  {
    id: 'pms',
    code: 'PMS',
    name: 'Purchasing',
    nameVi: 'Quản lý Mua hàng',
    description: 'Quản lý đơn mua hàng, nhà cung cấp, vật tư',
    icon: 'ShoppingCart',
    color: 'hsl(348, 75%, 46%)',
    href: '/dashboard/pms',
    group: 'operations',
    isEnabled: true,
    order: 4,
  },
  {
    id: 'qms',
    code: 'QMS',
    name: 'Quality',
    nameVi: 'Quản lý Chất lượng',
    description: 'Kiểm duyệt chất lượng, QA/QC tự động',
    icon: 'CheckCircle',
    color: 'hsl(348, 75%, 46%)',
    href: '/dashboard/qms',
    group: 'operations',
    isEnabled: true,
    order: 5,
  },
  {
    id: 'oms',
    code: 'OMS',
    name: 'Orders',
    nameVi: 'Quản lý Đơn hàng',
    description: 'Ghi nhận, đồng bộ đơn hàng toàn vẹn',
    icon: 'ClipboardList',
    color: 'hsl(348, 75%, 46%)',
    href: '/dashboard/oms',
    group: 'operations',
    isEnabled: true,
    order: 6,
  },
  {
    id: 'wms',
    code: 'WMS',
    name: 'Warehouse',
    nameVi: 'Quản lý Kho bãi',
    description: 'Quản lý kho bãi, cắt kho tự động, tồn kho',
    icon: 'Warehouse',
    color: 'hsl(348, 75%, 46%)',
    href: '/dashboard/wms',
    group: 'operations',
    isEnabled: true,
    order: 7,
  },
  {
    id: 'tms',
    code: 'TMS',
    name: 'Transport',
    nameVi: 'Quản lý Giao hàng',
    description: 'Logistics, giao nhận, tuyến đường, tracking',
    icon: 'Truck',
    color: 'hsl(348, 75%, 46%)',
    href: '/dashboard/tms',
    group: 'operations',
    isEnabled: true,
    order: 8,
  },

  // ── Nhóm: Support ─────────────────────────────────
  {
    id: 'ims',
    code: 'IMS',
    name: 'IT Management',
    nameVi: 'Quản lý CNTT',
    description: 'Bảo mật, audit logs, quản lý tenant, hạ tầng',
    icon: 'Server',
    color: 'hsl(38, 90%, 50%)',
    href: '/dashboard/ims',
    group: 'support',
    isEnabled: true,
    order: 9,
  },
  {
    id: 'hms',
    code: 'HMS',
    name: 'Human Resources',
    nameVi: 'Quản lý Nhân sự',
    description: 'Tổ chức, nhân viên, phòng ban, quỹ lương',
    icon: 'Users',
    color: 'hsl(38, 90%, 50%)',
    href: '/dashboard/hms',
    group: 'support',
    isEnabled: true,
    order: 10,
  },
  {
    id: 'ams',
    code: 'AMS',
    name: 'Accounting',
    nameVi: 'Quản trị Kế toán',
    description: 'Hạch toán, công nợ, hóa đơn tự động',
    icon: 'Calculator',
    color: 'hsl(38, 90%, 50%)',
    href: '/dashboard/ams',
    group: 'support',
    isEnabled: true,
    order: 11,
  },
  {
    id: 'cms',
    code: 'CMS',
    name: 'Controlling',
    nameVi: 'Quản trị & Kiểm soát',
    description: 'Kiểm soát rủi ro, ngân sách, cân đối lỗ lãi',
    icon: 'Gauge',
    color: 'hsl(38, 90%, 50%)',
    href: '/dashboard/cms',
    group: 'support',
    isEnabled: true,
    order: 12,
  },

  // ── Nhóm: Market ──────────────────────────────────
  {
    id: 'mms',
    code: 'MMS',
    name: 'Marketing Management',
    nameVi: 'Quản lý Marketing',
    description: 'Chiến dịch, phễu marketing, ROAS & Lead Funnel',
    icon: 'Megaphone',
    color: 'hsl(348, 75%, 46%)',
    href: '/dashboard/mms',
    group: 'market',
    isEnabled: true,
    order: 13,
  },
  {
    id: 'rms',
    code: 'RMS',
    name: 'R&D',
    nameVi: 'Nghiên cứu & Phát triển',
    description: 'Tạo mẫu, đổi mới sáng tạo, quản lý dự án R&D',
    icon: 'Lightbulb',
    color: 'hsl(348, 75%, 46%)',
    href: '/dashboard/rms',
    group: 'market',
    isEnabled: true,
    order: 14,
  },
  {
    id: 'sms',
    code: 'SMS',
    name: 'Sale Management',
    nameVi: 'Quản lý Bán hàng',
    description: 'Đội ngũ Sale thị trường, Leads, Deal & Hiệu suất',
    icon: 'TrendingUp',
    color: 'hsl(348, 75%, 46%)',
    href: '/dashboard/sms',
    group: 'market',
    isEnabled: true,
    order: 15,
  },
  {
    id: 'dms',
    code: 'DMS',
    name: 'Distributor',
    nameVi: 'Quản lý Phân phối',
    description: 'Mạng lưới đại lý, kênh phân phối',
    icon: 'Layers',
    color: 'hsl(348, 75%, 46%)',
    href: '/dashboard/dms',
    group: 'market',
    isEnabled: true,
    order: 16,
  },
];

export const MODULE_GROUPS = {
  bi: { name: 'Báo cáo', nameEn: 'BI & Reporting', icon: 'BarChart3' },
  operations: { name: 'Vận hành', nameEn: 'Operations', icon: 'Settings' },
  support: { name: 'Hỗ trợ', nameEn: 'Support', icon: 'Layers' },
  market: { name: 'Thị trường', nameEn: 'Market', icon: 'Globe' },
  system: { name: 'Hệ thống', nameEn: 'System', icon: 'Shield' },
} as const;

export function getModuleByCode(code: string): ModuleInfo | undefined {
  return MODULES.find((m) => m.code === code);
}

export function getModulesByGroup(group: ModuleInfo['group']): ModuleInfo[] {
  return MODULES.filter((m) => m.group === group).sort((a, b) => a.order - b.order);
}
